name: main

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "*.md"
    branches:
      - main
      - master
  pull_request:
    paths-ignore:
      - "*.md"
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version-file: ".tool-versions"
          cache: "npm"

      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Format
        run: npm run fmtcheck

  integration:
    if: github.event_name == 'push'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version-file: ".tool-versions"
          cache: "npm"

      - name: Turnstyle
        uses: ./ # Uses an action in the root directory
        with:
          poll-interval-seconds: 10

      - name: Deploy
        run: sleep 180
